### ISSUE TITLE
Name attribute should be in snake case, id should be in kebab case and in placeholder first letter only in capital

### ISSUE THREAD

**Issue by prasanth-j** [parthiban-sundaraj/event-management-system#2]
https://github.com/parthiban-sundaraj/event-management-system/blob/419dded290aa08b386d5802792f8da6325c509fa/create.html#L17

**Comment by parthiban-sundaraj** [comment]
In attribute Changed  for and id is kebeb case and name  is snake case also changed placeholde first letter only capital
